name: personal_info_manager
description: A Flutter application for managing personal information (appointments, contacts, notes, and tasks).

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^2.0.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.11
  flutter_slidable: ^3.1.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_calendar_carousel: ^2.4.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# Для изображений, шрифтов или других ресурсов добавьте секцию ниже
# assets:
#   - assets/images/
# fonts:
#   - family: CustomFont
#     fonts:
#       - asset: fonts/CustomFont-Regular.ttf
